app <- ShinyDriver$new("../", seed = 123)
app$snapshotInit("mytest")

app$setInputs(input_type = "")
app$snapshot()
app$setInputs(input_type = "internal_data")
app$snapshot()
app$setInputs(example_data = "ciel")
app$snapshot()
app$snapshot()
app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(tabs = "measures")
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(tabs = "about")
app$snapshot()
